name: m3u_baseUrl

on:
  schedule:
    - cron: "*/10 * * * *"  # Her 10 dakikada bir tetiklenir
  workflow_dispatch:        # Manuel çalıştırma için
  push:
    branches:
      - main
    paths:
      - ".github/workflows/m3u_baseUrl.yml"  # Bu dosya değiştiğinde tetiklenir

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Dosya kök dizindeyse yol değişmez

    - name: Run script
      run: python app.py  # Script dosyanızın adı ve yolu doğru olmalı

    - name: Add and commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "chore: Update file"
